apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: custom-domains-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - services/finalizers
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  - dnses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create

- apiGroups:
  - apps
  resourceNames:
  - custom-domains-operator
  resources:
  - deployments/finalizers
  verbs:
  - update

- apiGroups:
  - managed.openshift.io
  resources:
  - '*'
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch

- apiGroups:
  - operator.openshift.io
  resources:
  - ingresscontrollers
  verbs:
  - '*'

- apiGroups:
  - config.openshift.io
  resources:
  - dnses
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch

- apiGroups:
  - dnses.config.openshift.io
  resources:
  - '*'
  verbs:
  - create
  - get
  - list
  - watch

- apiGroups:
  - dnses.operator.openshift.io
  resources:
  - '*'
  verbs:
  - create
  - get
  - list
  - watch

- apiGroups:
  - ingress.operator.openshift.io
  resources:
  - dnsrecords
  verbs:
  - get
  - list
  - watch

- apiGroups:
  - config.openshift.io
  resources:
  - infrastructures
  verbs:
  - get
  - list
  - watch
